### ISSUE TITLE
Black video capturing on VDI with console session

### ISSUE THREAD

**Issue by bhecquet** [wrandelshofer/MonteMedia#3] opened 2019-05-28 15:11 UTC
Hello

I'm using your library for a while to capture video on local and remote windows physical computer using selenium grid. This worked well in both cases until then. On remote windows box, session remains open which is mandatory to get video working.

Now that I'm using it for capturing video on virtual remote computer, I get black video with the default settings. The session remains open on the virtual machine because I quit the remote desktop using "tscon X /dest:console".

I could not figure out what is wrong in this case. Some tests I've made
- if the session is opened through remote desktop while video is capturing, video is OK
- if the session is opened through remote desktop while ScreenRecorder is initialized, and then closed while capture is done, video is OK (tested with a debugger). It seems related to the `this.captureDevice = cfg.getDevice();` line
- if session is not opened inside remote desktop, video is black (KO)
- if session is not opened inside remote desktop, but MJPEG is , video is OK (but quite big)
- when I check the BufferedImage captured by Robot class, it's OK in all cases. 

It seems that the encoding or Quicktime / AVI packing step is causing the problem but I cannot find why.

Do you have any idea of what's going on ?

Thanks

**Comment by wrandelshofer** [comment] 2022-02-19 12:32
I have no idea what might be causing this - I have no setup with which I could reproduce it.
If the video is black, then the constructor of class ScreenGrabber might fail, because there is an unsupported  color depth, or method ScreenGrabber.grabScreen() might fail, because there is some illegal state in the Robot. There is a try-catch block in there that just skips IllegalMonitorStateException.

I suggest, that you run the screen recorder in a debugger and take a look at these methods.

**Comment by wrandelshofer** [comment] 2023-02-26 08:09
Closing this, because I can not reproduce it.

**Closed as completed by wrandelshofer** 2023-02-26 08:09 UTC
